apiVersion: v1
kind: Service
metadata:
  name: consumer-health-check-service
spec:
  selector:
    app: consumer-health-check-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP