apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  selector:
    matchLabels:
      app: health-check-service
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      containers:
        - name: health-check-service
          image: lioratari/health_check_service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: KAFKA_SERVER
            valueFrom:
              configMapKeyRef:
                name: health-check-service-cm
                key: kafka_server
          - name: KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
                name: health-check-service-cm
                key: kafka_topic