apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-check-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-check-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource: 
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
